baseurl = "https://starlixxx.github.io"
title = "Starlix's Website"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

[markup.highlight]
style = "github-light"

[params]
  author = "СЕКС ПОРНО БЕСПЛАТНО СКАЧАТЬ 18+ БЕЗ СМС И РЕГИСТРАЦИИ"
  info = "Пожалуйста, введите данные вашей карты что бы мы вам выделили 2 тб порнографии."
  description = "Starlix's personal website"
  keywords = "developer,personal"
  #avatarurl = "images/avatar.png"
  #gravatar = "beksultanbazuov@gmail.com"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2024

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/onesmiledx"

# Menu links
[[menu.main]]
  name = "About"
  weight = 1
  url = "about/"

[[menu.main]]
name = "Projects"
weight = 2
url = "projects/"

[[menu.main]]
name = "Contact me"
weight = 3
url = "contact/"
